version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
